"""Telegraph (telegra.ph) publisher - the easiest free webpost that exists.

Anonymous API: create an account token once, then publish instant pages.
Telegra.ph pages are DA ~88, index in Google, and support canonical authorship.
No signup, no email, no API key. Token is cached in data/.telegraph_token.
"""
from __future__ import annotations

import requests

from ..config import DATA_DIR, get_secret
from ..models import ArticleDraft, Persona, PostResult
from .base import UA, Publisher
from .htmlutil import html_to_telegraph_nodes, markdown_to_html

API = "https://api.telegra.ph"
TOKEN_FILE = DATA_DIR / ".telegraph_token"


def _token(persona: Persona) -> str:
    tok = get_secret("TELEGRAPH_TOKEN")
    if tok:
        return tok
    if TOKEN_FILE.exists():
        return TOKEN_FILE.read_text().strip()
    r = requests.get(f"{API}/createAccount",
                     params={"short_name": (persona.brand or persona.name)[:31],
                             "author_name": persona.name[:127]}, headers=UA, timeout=30)
    r.raise_for_status()
    tok = r.json()["result"]["access_token"]
    TOKEN_FILE.parent.mkdir(parents=True, exist_ok=True)
    TOKEN_FILE.write_text(tok)
    return tok


class TelegraphPublisher(Publisher):
    slug = "telegraph"
    name = "Telegra.ph"
    env_keys = []  # fully free & anonymous
    docs = "https://telegra.ph/api"

    def build_payload(self, draft: ArticleDraft, persona: Persona) -> dict:
        nodes = html_to_telegraph_nodes(markdown_to_html(draft.body_markdown))
        return {
            "access_token": "<auto-generated, cached in data/.telegraph_token>",
            "title": draft.title[:255],
            "author_name": persona.name[:127],
            "author_url": persona.website or "",
            "content": nodes,
            "return_content": False,
        }

    def _publish_live(self, draft, persona, payload, **kw) -> PostResult:
        payload["access_token"] = _token(persona)
        r = requests.post(f"{API}/createPage", json=payload, headers=UA, timeout=60)
        r.raise_for_status()
        result = r.json()
        if not result.get("ok"):
            return PostResult(self.slug, False, detail=str(result.get("error")))
        return PostResult(self.slug, True, url=result["result"]["url"], detail="page is live")
